#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

lappend auto_path [file join [file normalize [file dirname [info script]]] lib]
package require Tclx
signal -restart error SIGINT
package require Extral

if {[info commands "console"] == "console"} {
	console show
} else {
	commandloop -prompt1 {puts -nonewline "% "} -prompt2 {puts -nonewline ""}
}
